### ISSUE TITLE
Bug: Compare Result Summary

### ISSUE THREAD

**Issue by LakshmiKumar23** [kiritigowda/help#2]
Blank graph (with NULL values) when run the first time. Nothing to compare against.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 did you find this bug?

**Comment by LakshmiKumar23** [comment]
@kiritigowda Yes.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you push the bug fix

**Comment by LakshmiKumar23** [comment]
@kiritigowda I haven't fixed it yet. I will push it once I do.

**Comment by kiritigowda** [comment]
#3 fix in pipeline

**Comment by kiritigowda** [comment]
#3 merged
